# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OM_T3hHosEmCT0Ai5-2RhYMa46dc0INl
"""

# Yêu cầu: Nhập GPA (0-10) và phân loại
diem_so = float(input("Mời nhập điểm trung bình của sinh viên: "))

if diem_so < 0 or diem_so > 10:
    print("Dữ liệu nhập vào không hợp lệ.")
else:
    # Sử dụng cấu trúc rẽ nhánh để phân loại
    if diem_so >= 8.5:
        ket_qua = "Xuất sắc"
    elif diem_so >= 7.0:
        ket_qua = "Giỏi"
    elif diem_so >= 5.5:
        ket_qua = "Khá"
    elif diem_so >= 4.0:
        ket_qua = "Trung bình"
    else:
        ket_qua = "Yếu"

    print(f"Xếp loại học lực: {ket_qua}")

# Yêu cầu: Nhập n, tính tổng các số chẵn từ 1 đến n
n = int(input("Nhập một số nguyên dương n: "))
tong_chan = 0

# Duyệt qua các số từ 1 đến n
for i in range(1, n + 1):
    # Kiểm tra nếu là số chẵn (chia hết cho 2)
    if i % 2 == 0:
        tong_chan += i

print(f"Tổng các số chẵn từ 1 đến {n} là: {tong_chan}")

# Cấu hình mật khẩu và số lần thử
MAT_KHAU_DUNG = "python123"
so_lan_thu = 0
thanh_cong = False

# Cho phép nhập tối đa 3 lần
while so_lan_thu < 3:
    mk_nhap = input(f"Nhập mật khẩu (Lần {so_lan_thu + 1}): ")

    if mk_nhap == MAT_KHAU_DUNG:
        print("Đăng nhập thành công")
        thanh_cong = True
        break # Thoát vòng lặp ngay khi đúng
    else:
        so_lan_thu += 1
        if so_lan_thu < 3:
            print("Mật khẩu sai, vui lòng thử lại.")

# Sau 3 lần nếu vẫn không đúng
if not thanh_cong:
    print("Tài khoản bị khóa")