# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGxGO9_iiG2zNGF4H3zlsE9SNhDQ0w2C
"""

n = int(input("Enter a positive integer: "))
print(n)

s = 0   # biến dùng để lưu tổng

for i in range(0, n + 1):
    s += i     # cộng dồn

print(f"The sum of 0 to {n} is {s}")

